### PR TITLE
Allow using a Parquet file during join/merge

### PR DESCRIPTION
**Pull request by kylebarron**
In case you're interested, this is a small edit to support using [`stata-parquet`](https://github.com/mcaceresb/stata-parquet) for the using dataset in `join`/`fmerge`. 

Parquet files are very performant, especially when loading only a few columns of a very wide dataset.

cc: @mcaceresb

### CODE REVIEW

**Comment by sergiocorreia** [comment]
That's amazing! I love parquet files and would definitely like them to be more broadly used through Stata.

**Comment by mcaceresb** [comment]
Very cool! Note that the plugin only works for Linux/Unix atm. We haven't quite implemented a cross-platform solution.

**Comment by sergiocorreia** [comment]
Dang! BTW are there any fundamental reasons for that, or just that your setup is linux-exclusive? (which is a valid reason!)

**Comment by kylebarron** [comment]
Great! @sergiocorreia 	You may want to double check that I modified the if-then logic appropriately. I haven't used `unab` before, but it appears that that can only be used once the dataset of interest is in memory.

Also, this PR only currently supports `.parquet` files being the `` `from' `` dataset , not the `` `into'`` dataset. To support the latter, I'd have to put two commands inside the `` `cmd'`` local here:
https://github.com/sergiocorreia/ftools/blob/13541e3be6cb02640f7f433b625ec1388496d8ed/src/join.ado#L86

That's because the `parquet use` command doesn't support `if`. So the first command would have to load it and the second would have to run ``keep `if'``

**Comment by kylebarron** [comment]
I don't think there are any fundamental reasons for no Mac/Windows support. 

I got errors last night when attempting the current installation on Mac, and have never tried on Windows.

I think if we wanted to attempt a cross-platform installation method, having the install be a conda package would probably be easiest (unless Mauricio figured out how to compile the library fully 100% statically). No Windows user will be able to compile a C++ package themselves...

**Comment by mcaceresb** [comment]
We wanted to make it cross platform but failed when we tried. Will revisit eventually but you're welcome to take a stab at it! @kylebarron did some work on this already. See [here](github.com/mcaceresb/stata-parquet/issues/6) and [here](https://github.com/mcaceresb/stata-parquet/issues/5).

**Comment by kylebarron** [comment]
I attempted to write the metadata to allow a Conda package (https://github.com/kylebarron/stata-parquet/commit/59bd9dde8c1535679d5817e10c07bb7a270b7bf9) but the output library didn't seem to work.

(It's basically just a `build.sh` script for Mac/Linux and a `build.bat` script for Windows)
https://conda.io/projects/conda-build/en/latest/source/build-scripts.html

**Comment by sergiocorreia** [comment]
> Great! @sergiocorreia You may want to double check that I modified the if-then logic appropriately. I haven't used `unab` before, but it appears that that can only be used once the dataset of interest is in memory.

The only thing I see is related to the `if` option [here](https://github.com/sergiocorreia/ftools/blob/13541e3be6cb02640f7f433b625ec1388496d8ed/src/join.ado#L81):

```stata
if (`"`if'"' != "") qui keep `if'
````

Since `parquet use` does not support `if`, a problem might arise if `if` mentions variables not loaded. Something like:

```stata
parquet use price weight gear using "example.parquet", clear
keep if foreign==1 // --> Error
```

An assert right before `parquet use` might fix this. (Unrelated, but I prefer the undocumented `_assert` command for those things, as it allows me to check a condition, use a specific return code, AND an error message all in one line).

Alternatively, if there's an if clause then you might want to play it safe and load everything (but that's agianst the hole point of parquet I guess?)

---

> To support the latter, I'd have to put two commands inside the `cmd' local here

If we are disabling `if` in the previous case, we might want to disable it here. Or have a custom program at the end that just contain the two lines (`parquet use` + `keep if`).

> Will revisit eventually but you're welcome to take a stab at it! 

I'm quite tempted to! But will probably keep it on the back burner until I reduce the things I have on my plate..

**Comment by kylebarron** [comment]
> An assert right before `parquet use` might fix this. (Unrelated, but I prefer the undocumented `_assert` command for those things, as it allows me to check a condition, use a specific return code, AND an error message all in one line).

Do you know how to assert that the `if` statement uses only variables in a given list?

> Alternatively, if there's an if clause then you might want to play it safe and load everything (but that's agianst the whole point of parquet I guess?)

Yes that would be against the point.

> > To support the latter, I'd have to put two commands inside the `cmd' local here
> 
> If we are disabling `if` in the previous case, we might want to disable it here. Or have a custom program at the end that just contain the two lines (`parquet use` + `keep if`).

I'm not sure what the best course of action is here

**Comment by sergiocorreia** [comment]
> Do you know how to assert that the `if` statement uses only variables in a given list?

I'm not aware of a way to do it. For instance, Stata allows variable abbreviations, factor variables, etc. A simple option might be to do something like `use in 1`; `keep if ..` but not sure how long the first clause takes in parquet.

**Comment by kylebarron** [comment]
> A simple option might be to do something like `use in 1`; `keep if ..`

That isn't possible in Parquet. Since parquet files are column oriented, the only possibility is reading the entire column (unless if the Parquet file was saved with multiple "row groups", in which case you'd have to read N rows of any given column, where N is the length of the row group.)

**Comment by mcaceresb** [comment]
> That isn't possible in Parquet.

That's just not true (: 

```stata
. sysuse auto, clear
(1978 Automobile Data)

. expand 100000
(7,399,926 observations created)

. parquet save auto.parquet, replace
Copied data into Arrow table (2.79 sec).
Wrote table to file (1.42 sec).

. parquet use auto.parquet, in(1) clear
Scanned column types (0.00 sec).
Read data from disk (0.00 sec).

. assert _N == 1                 

. parquet use auto.parquet, clear      
Scanned column types (0.08 sec).
Read data from disk (2.42 sec).

. assert _N == `=74 * 100000'
```

**Comment by kylebarron** [comment]
I had no idea it's possible to do that. Why the non-standard `in()` syntax?

**Comment by mcaceresb** [comment]
The more you know.

**Comment by kylebarron** [comment]
Why not use `in` instead of `in()` as an option?

**Comment by mcaceresb** [comment]
`in`, like `if`, checks the data in memory, not the data being loaded.

**Comment by kylebarron** [comment]
How does `use in 1/50 if ... using auto.dta` work? They have a special workaround?

**Comment by mcaceresb** [comment]
_Edit_: I just realized you asked something else. Yes, I think they have a special workaround for built in commands.

**Comment by kylebarron** [comment]
That's very smart. I intended to ask how the official Stata `use` command is able to use the normal `if` and `in` syntax when the data doesn't exist in memory yet...

**Pull request merged**
